# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_detection', '0002_auto_20170908_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='data',
            field=models.ImageField(upload_to='uploaed_images'),
        ),
    ]
