# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_detection', '0003_auto_20170908_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='data',
            field=models.ImageField(upload_to='uploaded_images'),
        ),
    ]
