# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_detection', '0005_auto_20170908_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='data',
            new_name='image',
        ),
    ]
